version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DEBUG: 1

   phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     restart: always
     ports:
      - "8080:80"
     links:
      - db:db

   wpcli:
     depends_on:
      - db
      - wordpress    
     image: wordpress:cli
     # vstm: This is required to run wordpress-cli with the same
     # user-id as wordpress. This way there are no permission problems
     # when running the cli
     user: xfs
     # vstm: The sleep 10 is required so that the command is run after
     # mysql is initialized. Depending on your machine this might take
     # longer or it can go faster.
     # vstm: add shared volume (wp-app) 
     volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
     restart: always
     depends_on:
      - db
      - wordpress

volumes:
    db_data: {}
    # vstm: add shared volume
    wp-app:
 

